{{- if and .Values.sshpiper.vault.enabled .Values.sshpiper.vault.token (not .Values.sshpiper.vault.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sshpiper.fullname" . }}-vault
  labels:
    {{- include "sshpiper.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.sshpiper.vault.token | quote }}
{{- end }}
