{{- if .Values.sshpiper.trustedUserCAKeys }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sshpiper.fullname" . }}-ca
  labels:
    {{- include "sshpiper.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $name, $content := .Values.sshpiper.trustedUserCAKeys }}
  {{ $name }}: |
    {{- $content | nindent 4 }}
  {{- end }}
{{- end }}
