apiVersion: v2
name: sshpiper
description: The missing reverse proxy for ssh scp, username based SSH Reverse Proxy
type: application
version: 0.5.0-dc1
appVersion: "v1.5.4-dc1"

sources:
  - https://github.com/datacosmos-br/sshpiper
  - https://github.com/datacosmos-br/sshpiper-chart
  - https://github.com/tg123/sshpiper

maintainers:
  - name: Datacosmos
    url: https://github.com/datacosmos-br
  - name: Boshi Lian
    email: farmer1992@gmail.com
    url: https://github.com/tg123

keywords:
  - "ssh"
  - "scp"
  - "reverse proxy"
  - "sshpiper"
  - "ca"
  - "vault"
